services:
  tcdatalogger:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: tcdatalogger
    volumes:
      - ./config:/app/config:ro
      - ./var/log:/app/var/log
      - ./var/data:/app/var/data
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/credentials.json
    init: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*main.py"]
      interval: 5m
      timeout: 3s
      retries: 3
    restart: unless-stopped 